---
- name: Install dnsmasq
  homebrew: name=dnsmasq state=present

- name: Configure dnsmasq
  copy: src=dnsmasq.conf dest=/usr/local/etc/dnsmasq.conf

- name: Make /etc/resolver
  file:
    path: /etc/resolver
    group: admin
    mode: 0755
    state: directory
  become: yes

- name: Configure dnsmasq to serve *.dev
  copy: src=resolver.dev dest=/etc/resolver/dev
  become: yes
  
- name: Start dnsmasq
  shell: brew services start dnsmasq
  become: yes
